wagtail_tenants/customers/models.py
from django.db import models
from django_tenants.models import DomainMixin, TenantMixin
from django_tenants.utils import schema_context


class ClientFeature(models.Model):
    name = models.CharField(max_length=100)
    menu_name = models.CharField(max_length=100, blank=True, null=True)
    app_label = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

    wagtail_reference_index_ignore = True


class ClientFeatureGroup(models.Model):
    name = models.CharField(max_length=100)
    features = models.ManyToManyField(ClientFeature, blank=True)

    def __str__(self):
        return self.name

    wagtail_reference_index_ignore = True


class Client(TenantMixin):
    name = models.CharField(max_length=100)
    paid_until = models.DateField()
    on_trial = models.BooleanField()
    created_on = models.DateField(auto_now_add=True)
    features = models.ManyToManyField(ClientFeature, blank=True)
    plan = models.ForeignKey(
        ClientFeatureGroup,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tenants",
    )
    # default true, schema will be automatically created and synced when it is saved
    auto_create_schema = True
    auto_drop_schema = True

    def save(self, *args, **kwargs):
        with schema_context("public"):
            super(Client, self).save(*args, **kwargs)

    """
    This has to be implemented in terms of not referencing the new reference index
    see: https://github.com/wagtail/wagtail/issues/9731
    """
    wagtail_reference_index_ignore = True


class ClientBackup(models.Model):
    client = models.ForeignKey(
        Client, related_name="client_backups", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    filename = models.CharField(null=True, blank=True, max_length=80)

    """
    This has to be implemented in terms of not referencing the new reference index
    see: https://github.com/wagtail/wagtail/issues/9731
    """
    wagtail_reference_index_ignore = True


class Domain(DomainMixin):
    def save(self, *args, **kwargs):
        with schema_context("public"):
            super(Domain, self).save(*args, **kwargs)

    ...
    """
    This has to be implemented in terms of not referencing the new reference index
    see: https://github.com/wagtail/wagtail/issues/9731
    """
    wagtail_reference_index_ignore = True

wagtail_tenants/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models, connection
from wagtail.admin.panels import FieldPanel

from wagtail_tenants.customers.models import Client


# Create your models here.
class User(AbstractUser):
    ...
    tenant = models.ForeignKey(
        Client,
        related_name="tenant_user",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    """
    This has to be implemented in terms of not referencing the new reference index
    see: https://github.com/wagtail/wagtail/issues/9731
    """
    wagtail_reference_index_ignore = True


class SmtpAuthenticator(models.Model):
    tenant = models.ForeignKey(
        Client,
        related_name="tenant_smtp_auth",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    site = models.OneToOneField(
        "wagtailcore.Site",
        related_name="smtp_auth",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    smtp_user = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        help_text="Leave blank to use the same username as the email address.",
    )
    email = models.EmailField()
    smtp_password = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        help_text="Leave blank to use the same password as the email address.",
    )
    smtp_host = models.CharField(max_length=100)
    smtp_port = models.PositiveIntegerField(default=587)
    use_tls = models.BooleanField(default=False)
    fail_silently = models.BooleanField(default=True)
    use_ssl = models.BooleanField(default=False)
    timeout = models.PositiveIntegerField(null=True, blank=True)
    ssl_keyfile = models.FileField(null=True, blank=True)
    ssl_certfile = models.FileField(null=True, blank=True)

    wagtail_reference_index_ignore = True

    panels = [
        FieldPanel("site"),
        FieldPanel("smtp_user"),
        FieldPanel("smtp_password"),
        FieldPanel("email"),
        FieldPanel("smtp_host"),
        FieldPanel("smtp_port"),
        FieldPanel("fail_silently"),
        FieldPanel("timeout"),
        FieldPanel("use_tls"),
        FieldPanel("use_ssl"),
        FieldPanel("ssl_keyfile"),
        FieldPanel("ssl_certfile"),
    ]

    def save(self, *args, **kwargs):
        ## Ensure that the tenant is the current tenant
        self.tenant = connection.tenant
        if not self.site:
            raise ValueError("A site is required")
        super(SmtpAuthenticator, self).save(*args, **kwargs)

wagtail_tenants/users/models.py
from django.contrib.auth.models import Group
from django.db import models


class TenantGroupManager(models.Manager):
    use_in_migrations = True

    def get_by_natural_key(self, name):
        return self.get(name=name)


class TenantGroup(Group):
    class Meta:
        proxy = True

    objects = TenantGroupManager()

wagtail_tenants/forms.py
from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from wagtail import hooks
from wagtail.users.forms import GroupForm
from wagtail.admin.forms.models import WagtailAdminModelForm
from wagtail_tenants.customers.models import Client
from wagtail_tenants.models import SmtpAuthenticator

from .utils import filter_permissions_reserved_for_superuser

UserModel = get_user_model()


class TenantAdminUserForm(forms.Form):
    superusers = UserModel.objects.filter(is_staff=True)
    tenants = Client.objects.exclude(schema_name="public")

    superuser = forms.ModelChoiceField(superusers, label="Admin")
    tenant = forms.ModelChoiceField(tenants, label="Tenant")


class TenantAwareGroupForm(GroupForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        current_tenant = kwargs.pop("tenant", None)
        super().__init__(*args, **kwargs)

        for fn in hooks.get_hooks("register_permissions"):
            self.registered_permissions = self.registered_permissions | fn()

        # Get the content type IDs to exclude
        content_type_ids_to_exclude = []
        if user:
            if not user.is_superuser:
                content_type_ids_to_exclude = filter_permissions_reserved_for_superuser(
                    current_tenant, self.registered_permissions
                )
            ...

        aviable_permissions = self.registered_permissions.exclude(
            content_type__id__in=content_type_ids_to_exclude
        )
        self.fields["permissions"].queryset = aviable_permissions.select_related(
            "content_type"
        )


class SmtpAuthenticatorForm(WagtailAdminModelForm):
    class Meta:
        model = SmtpAuthenticator
        exclude = ("tenant",)  # Exclude the 'tenant' field from the form

wagtail_tenants/customers/views.py
from django.shortcuts import render

# Create your views here.

wagtail_tenants/middleware/main.py
from django_tenants.middleware.main import TenantMainMiddleware


class WagtailTenantMainMiddleware(TenantMainMiddleware):
    ...


from django.apps import apps
from django.shortcuts import redirect
from django_tenants.utils import get_tenant_model


class WagtailTenantPermissionMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.check_tenant_permission(request)
        return response

    def check_tenant_permission(self, request):
        # Get the current tenant
        current_tenant = get_tenant_model().objects.get(
            schema_name=request.tenant.schema_name
        )

        # Get the app's AppConfig
        for app_config in apps.get_app_configs():
            if hasattr(app_config, "allow_tenant"):
                if app_config.name in request.path:
                    # Check if the user's tenant matches the AppConfig property
                    if current_tenant.schema_name != app_config.allow_tenant:
                        return redirect("wagtailadmin_home")

        return self.get_response(request)

wagtail_tenants/users/views/users.py
from wagtail.users.views.users import Index as WagtailUsersIndex
from wagtail.users.views.users import Create as WagtailUsersCreate
from wagtail.users.views.users import Edit as WagtailUsersEdit
from wagtail.users.views.users import Delete as WagtailUsersDelete

from wagtail.users.views.users import get_users_filter_query
from django.db.models import Q
from django.db import transaction
from wagtail_tenants.models import User
from wagtail_tenants.utils import check_tenant_for_user, is_client_tenant


class Index(WagtailUsersIndex):
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.tenant = request.tenant
        self.tenant_filter = Q()
        if request.tenant and is_client_tenant(request.tenant):
            self.tenant_filter = Q(tenant=self.tenant)

    def get_queryset(self):
        model_fields = set(self.model_fields)
        print()
        if self.is_searching:
            conditions = get_users_filter_query(self.search_query, model_fields)
            users = User.objects.filter(
                self.group_filter & conditions & self.tenant_filter
            )
        else:
            users = User.objects.filter(self.group_filter & self.tenant_filter)

        if self.locale:
            users = users.filter(locale=self.locale)

        if "wagtail_userprofile" in model_fields:
            users = users.select_related("wagtail_userprofile")

        if "last_name" in model_fields and "first_name" in model_fields:
            users = users.order_by("last_name", "first_name")

        if self.get_ordering() == "username":
            users = users.order_by(User.USERNAME_FIELD)

        return users

    ...


class Create(WagtailUsersCreate):
    ...

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.tenant = request.tenant

    def form_valid(self, form):
        self.form = form
        with transaction.atomic():
            self.object = self.save_instance()
            self.object.tenant = self.tenant
            self.object.save()

        response = self.save_action()

        hook_response = self.run_after_hook()
        if hook_response is not None:
            return hook_response

        return response


class Edit(WagtailUsersEdit):
    template_name = "wagtailusers/users/edit.html"
    ...


class Delete(WagtailUsersDelete):
    ...

wagtail_tenants/views.py
from django.db import transaction
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext as _
from django_tenants.utils import tenant_context
from wagtail.admin import messages
from wagtail.admin.views import account
from wagtail.log_actions import log
from wagtail.users.views.groups import CreateView, EditView, GroupViewSet

from wagtail_tenants.backends import UserModel
from wagtail_tenants.forms import TenantAdminUserForm
from wagtail_tenants.utils import check_tenant_for_user

from .forms import TenantAwareGroupForm


class TenantLoginView(account.LoginView):
    def get(self, *args, **kwargs):

        if (
            check_tenant_for_user(self.request.user, self.request.tenant)
            and self.request.user.is_authenticated
            and self.request.user.has_perm("wagtailadmin.access_admin")
        ):
            return redirect(self.get_success_url())

        return super().get(*args, **kwargs)


class TenantUserAdmin:
    def create(request, *args):
        if request.method == "POST":
            form = TenantAdminUserForm(request.POST)
            if form.is_valid():
                superuser = form.cleaned_data["superuser"]
                tenant = form.cleaned_data["tenant"]
                with tenant_context(tenant):
                    created = False
                    try:
                        tenant_admin = UserModel.objects.get(
                            username=superuser.username
                        )
                    except UserModel.DoesNotExist:
                        tenant_admin = UserModel(
                            username=superuser.username,
                            email=superuser.email,
                            password=superuser.password,
                            is_staff=True,
                            is_superuser=True,
                        )
                        tenant_admin.save()
                        created = True

                    if created:
                        print("New SuperAdmin added to Tenant")
                        # log(tenant_admin, "wagtail-tenants__admin.link")
                        messages.success(
                            request,
                            _("Admin to Tenant link '{0}' created.").format(
                                tenant_admin
                            ),
                            buttons=[
                                # messages.button(
                                #     reverse("wagtailusers_users:edit", args=(user.pk,)), _("Edit")
                                # )
                            ],
                        )
                        ...
                        return redirect("wagtail-tenants__admin_link")
                    messages.warning(
                        request,
                        _("Admin to Tenant link '{0}' exist.").format(tenant_admin),
                        buttons=[
                            messages.button(
                                tenant.domains.get(is_primary=True).domain, _("Login")
                            )
                        ],
                    )
                    return redirect("wagtail-tenants__admin_link")

        else:
            form = TenantAdminUserForm()
            return TemplateResponse(
                request,
                "wagtail_tenants/admin/link.html",
                {
                    "form": form,
                },
            )


class TenantAwareGroupCreateView(CreateView):
    def get_form_kwargs(self):
        """Passes the user to the form class.
        This is necessary to only display members that belong to a given user
        """

        kwargs = super(CreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        kwargs["tenant"] = self.request.tenant
        return kwargs


class TenantAwareGroupEditView(EditView):
    def get_form_kwargs(self):
        """Passes the user to the form class.
        This is necessary to only display members that belong to a given user
        """

        kwargs = super(EditView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        kwargs["tenant"] = self.request.tenant
        return kwargs


class TenantAwareGroupViewSet(GroupViewSet):
    add_view_class = TenantAwareGroupCreateView
    edit_view_class = TenantAwareGroupEditView

    def get_form_class(self, for_update=False):
        return TenantAwareGroupForm

wagtail_tenants/templates/wagtailusers/_groups/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Delete group" %}{% endblock %}

{% block content %}
    {% trans "Delete group" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=group.name icon="group" %}

    <div class="nice-padding">
        <p>
            {% blocktrans trimmed with group_name=group.name count group_user_count=group.user_set.count %}
                The group '{{ group_name }}' has <strong>{{ group_user_count }}</strong> member.
            {% plural %}
                The group '{{ group_name }}' has <strong>{{ group_user_count }}</strong> members.
            {% endblocktrans %}
        </p>
        <p>
            {% if group.user_set.count %}
                {% trans "Deleting this group will revoke this group's permissions from all member users." %}
            {% endif %}
        </p>

        <p>{% trans "Are you sure you want to delete this group?" %}</p>
        <form action="{% url 'wagtailusers_groups:delete' group.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Yes, delete' %}" class="button serious" />
        </form>
    </div>
{% endblock %}

wagtail_tenants/templates/wagtailusers/_groups/create.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailusers_tags wagtailimages_tags wagtailadmin_tags i18n %}

{% block titletag %}{% trans "Add group" %}{% endblock %}

{% block extra_css %}
    {{ block.super }}

    {{ form_media.css }}
{% endblock %}

{% block content %}

    {% trans "Add group" as add_group_str %}
    {% include "wagtailadmin/shared/header.html" with title=add_group_str icon="group" only %}

    <div class="nice-padding">
        <form action="{% url 'wagtailusers_groups:add' %}" method="POST" novalidate>
            {% csrf_token %}

            <ul class="fields">
                {% block fields %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=form.name %}
                    {% block extra_fields %}{% endblock extra_fields %}
                {% endblock fields %}
                <li>
                    {% format_permissions permission_bound_field=form.permissions %}
                </li>
                {% for panel in permission_panels %}
                    <li>
                        {{ panel.as_admin_panel }}
                    </li>
                {% endfor %}
                <li><input type="submit" value='{% trans "Add group" %}' class="button" /></li>
            </ul>
        </form>
    </div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "wagtailusers/groups/includes/group_form_js.html" %}
{% endblock %}

wagtail_tenants/templates/wagtailusers/_groups/edit.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailusers_tags wagtailadmin_tags i18n %}

{% block titletag %}{% trans "Editing" %} {{ group.name }}{% endblock %}

{% block extra_css %}
    {{ block.super }}

    {{ form_media.css }}
{% endblock %}

{% block content %}

    {% trans "Editing" as editing_str %}
    {% trans "View users in this group" as users_str %}
    {% url 'wagtailusers_groups:users' group.id as group_users_url %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str action_icon="user" action_url=group_users_url action_text=users_str subtitle=group.name icon="group" %}

    <div class="nice-padding">
        <form action="{% url 'wagtailusers_groups:edit' group.id %}" method="POST" novalidate>
            {% csrf_token %}

            <div class="fields">
                {% block fields %}
                    {% panel id="name" heading=form.name.label id_for_label=form.name.id_for_label is_required=True %}
                        {% include "wagtailadmin/shared/field.html" with field=form.name show_label=False %}
                    {% endpanel %}
                    {% block extra_fields %}{% endblock extra_fields %}
                {% endblock fields %}

                <div>
                    {% format_permissions permission_bound_field=form.permissions %}
                </div>

                {% for panel in permission_panels %}
                    <div>
                        {{ panel.as_admin_panel }}
                    </div>
                {% endfor %}
                <div>
                    <input type="submit" value="{% trans 'Save' %}" class="button" />

                    {% if perms.auth.delete_group %}
                        <a href="{% url 'wagtailusers_groups:delete' group.id %}" class="button no">{% trans "Delete group" %}</a>
                    {% endif %}
                </div>
            </div>

        </form>
    </div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "wagtailusers/groups/includes/group_form_js.html" %}
{% endblock %}

wagtail_tenants/templates/wagtailusers/_groups/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{{ page_title }}{% endblock %}
{% block extra_js %}
    {{ block.super }}
    <script>
        window.headerSearch = {
            url: "{% url view.index_url_name %}",
            termInput: "#id_q",
            targetOutput: "#group-results"
        }
    </script>
{% endblock %}

{% block content %}
    {% url view.add_url_name as add_link %}
    {% include "wagtailadmin/shared/header.html" with title=page_title action_url=add_link action_text=view.add_item_label icon=header_icon search_url=view.index_url_name %}

    <div class="nice-padding">
        <div id="group-results" class="groups">
            {% include "wagtailusers/groups/results.html" %}
        </div>
    </div>
{% endblock %}

wagtail_tenants/templates/wagtailusers/_groups/results.html
{% load i18n wagtailadmin_tags %}

{% if groups %}
    {% component table %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=page_obj linkurl="wagtailusers_groups:index" %}
{% elif is_searching %}
    <p role="alert">{% blocktrans trimmed with query=search_form.q.value %}Sorry, no groups match "{{ query }}"{% endblocktrans %}</p>
{% else %}
    {% url 'wagtailusers_groups:add' as wagtailusers_create_group_url %}
    <p>{% blocktrans trimmed %}There are no groups configured. Why not <a href="{{ wagtailusers_create_group_url }}">add some</a>?{% endblocktrans %}</p>
{% endif %}